### ISSUE TITLE
Completar tablas/matrices

### ISSUE THREAD

**Issue by Adrielram** [equisdel/compiler-from-scratch#8]

**Comment by equisdel** [comment]
https://docs.google.com/spreadsheets/d/1-vsDUb-IUbD1udw1csHFIdPgrW8KWVV5PTZhkjambjY/edit?gid=0#gid=0.
La matriz se hardcodea o será posible que la lea directo del archivo de Google Sheets?

**Comment by equisdel** [comment]
Falta la matriz de acciones semánticas.
Falta refinar detalles de la matriz de transición de estados (corregir algunas cuestiones).
